apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
    environment: student-devops
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP