name: GCP Production Deployment

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: "future-grove-439612-s8"
  GKE_CLUSTER: "student-devops-cluster"
  REGION: "us-central1"

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Verify billing and services
      run: |
        echo "🔍 Checking project status..."
        gcloud projects describe $PROJECT_ID
        echo "✅ Project is active"
        
        echo "🔍 Checking billing..."
        gcloud billing projects describe $PROJECT_ID || echo "⚠️  Billing check failed - continuing deployment"

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io --quiet

    - name: Build Docker image
      run: |
        echo "🐳 Building Docker image..."
        docker build -t gcr.io/$PROJECT_ID/web-app:$GITHUB_SHA .
        docker tag gcr.io/$PROJECT_ID/web-app:$GITHUB_SHA gcr.io/$PROJECT_ID/web-app:latest
        docker images

    - name: Push Docker image to GCR
      run: |
        echo "📤 Pushing to Container Registry..."
        docker push gcr.io/$PROJECT_ID/web-app:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/web-app:latest
        echo "✅ Images pushed successfully"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Create Infrastructure with Terraform
      run: |
        echo "🏗️  Creating GKE cluster with Terraform..."
        cd terraform
        terraform init
        terraform plan -var="project_id=$PROJECT_ID"
        terraform apply -auto-approve -var="project_id=$PROJECT_ID"
        echo "✅ Infrastructure created successfully"

    - name: Configure kubectl
      run: |
        echo "🔧 Configuring Kubernetes access..."
        gcloud container clusters get-credentials $GKE_CLUSTER --region $REGION
        kubectl cluster-info
        echo "✅ Kubernetes access configured"

    - name: Deploy Application
      run: |
        echo "🎯 Deploying application to GKE..."
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        
        echo "⏳ Waiting for deployment to complete..."
        kubectl rollout status deployment/web-app --timeout=300s
        echo "✅ Application deployed successfully"

    - name: Get Application URL
      run: |
        echo "🌐 Getting application information..."
        kubectl get services --namespace=default
        
        echo ""
        echo "🎉 DEPLOYMENT SUCCESSFUL!"
        echo "📊 Project: $PROJECT_ID"
        echo "🏷️  Cluster: $GKE_CLUSTER"
        echo "📍 Region: $REGION"
        echo "🐳 Image: gcr.io/$PROJECT_ID/web-app:latest"
        echo ""
        echo "🔗 Your application will be available at the EXTERNAL-IP shown above"
        echo "⏰ It may take 2-5 minutes for the LoadBalancer to provision"

    - name: Create Deployment Report
      run: |
        echo "# GCP Deployment Report" > DEPLOYMENT_REPORT.md
        echo "## Project: $PROJECT_ID" >> DEPLOYMENT_REPORT.md
        echo "## Status: ✅ DEPLOYED SUCCESSFULLY" >> DEPLOYMENT_REPORT.md
        echo "### Deployment Details:" >> DEPLOYMENT_REPORT.md
        echo "- GKE Cluster: $GKE_CLUSTER" >> DEPLOYMENT_REPORT.md
        echo "- Region: $REGION" >> DEPLOYMENT_REPORT.md
        echo "- Docker Image: gcr.io/$PROJECT_ID/web-app:latest" >> DEPLOYMENT_REPORT.md
        echo "- Terraform: Infrastructure as Code" >> DEPLOYMENT_REPORT.md
        echo "- Kubernetes: Container Orchestration" >> DEPLOYMENT_REPORT.md
        echo "- CI/CD: GitHub Actions" >> DEPLOYMENT_REPORT.md