name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: devops-project-cluster
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker gcr.io

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/web-app:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/web-app:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --region $REGION
        kubectl set image deployment/web-app web-app=gcr.io/$PROJECT_ID/web-app:$GITHUB_SHA
        kubectl rollout status deployment/web-app